Adding details to README for ACA data analysis.
ConnectedSystems/GBR-Bathy10m pull request #10
Opened 2024-05-15 22:28 UTC by BG-AIMS

Detailed data structures for ACA and Wave data, ACA crs and the intent of each numbered script.

2024-05-16 08:07 UTC, ConnectedSystems commented on README.md
> +WAVE_DATA_DIR : contains wave NetCDF data at GBRMPA-management-region scale.
Something like this?

```suggestion
WAVE_DATA_DIR : contains wave data in NetCDF format at the scale of GBRMPA management regions.
```

2024-05-16 08:08 UTC, ConnectedSystems commented on README.md
> +
```suggestion
│   └───Vector data
└───Turbidity-Q3-2023
    └───Raster data

```

2024-05-16 08:08 UTC, ConnectedSystems commented on README.md
>  │   └───Townsville-Whitsunday
```suggestion
└───Tp
    ├───Cairns-Cooktown
    ├───FarNorthern
    ├───Mackay-Capricorn
    └───Townsville-Whitsunday
```

2024-05-16 08:09 UTC, ConnectedSystems commented on README.md
> +https://www.allencoralatlas.org/
Spacing is needed

```suggestion
### ACA data

https://www.allencoralatlas.org/
```

2024-05-16 08:10 UTC, ConnectedSystems requested changes
Minor formatting

2024-05-19 23:21 UTC, ryulippmann commented on README.md
> +`ACA raster data` (Bathymetry, Turbidity, Waves) : 10 x 10m pixel size
Separate waves as standalone dataset, netCDF format

2024-05-20 06:11 UTC, merged