Reprojecting input and result data to GDA-2020
ConnectedSystems/GBR-Bathy10m pull request #12
Opened 2024-05-17 06:23 UTC by BG-AIMS

Added scripts to reproject all raster data to GDA 2020 and uses GBR features and management areas datasets that are now in GDA2020. 
Still need 'old' GDA94 reef features dataset for it's 'Area_HA' column.

2024-05-17 07:07 UTC, ConnectedSystems requested changes
Few minor changes, thanks

2024-05-17 07:07 UTC, ConnectedSystems commented on README.md
> +GDA2020_DATA_DIR = "path to GBR and management region feature datasets in crs GDA2020"
```suggestion
GDA2020_DATA_DIR = "path to GBR management region feature datasets in EPSG:7844 (GDA2020)"
```

2024-05-17 07:07 UTC, ConnectedSystems commented on src/3a_count_MPA.jl
>  )
FYI, this can now be outputted to geopackage. Figured out what I was doing wrong getting the data into ArcGIS (definitely user error)

2024-05-17 07:07 UTC, ConnectedSystems commented on README.md
> +`Tp` (Peak wave period) : Peak wave energy period, in seconds.
Document somewhere it is `Tp90` and `Hs90` (90th percentile data)

2024-05-19 23:30 UTC, ryulippmann commented on src/2a_analyze_MPA.jl
> +        # that meet criteria of (-9 <= depth <= -3m, slope < 40 deg, habitat is Rock or
-9 <= depth <= -2m

2024-05-19 23:34 UTC, ryulippmann commented on src/2a_analyze_MPA.jl
comment desciption to match values and format of criteria below
```suggestion
        # that meet criteria of (benthic habitat is Rock or Coral/Algae, -9 <= depth <= -2m, 
        # slope < 40 deg, 90th percentile of standing wave height <= 1m, and wave period <= 6 sec).

```

2024-05-19 23:36 UTC, ryulippmann commented on src/common.jl
> +    global GDA2020_DATA_DIR = CONFIG["gda2020_data"]["GDA2020_DATA_DIR"]
move global WAVE_DATA_DIR to this block
```suggestion
    global GDA2020_DATA_DIR = CONFIG["gda2020_data"]["GDA2020_DATA_DIR"]
```

2024-05-20 00:56 UTC, merged

2024-05-20 00:57 UTC, ryu-AIMS commented
README suggested changes seem to be made in commit 9a88f39afe3e8dcdb7cfbc5e239389b92d303509